//! The word of `ship_flight_stats` that the executable holds rather than `shipstats.bin`: for
//! each ship type, how the AI turns it.
//!
//! Generated by `src/tools/tablegen` from the payload executable's `ship_flight_stats` at
//! 0x004F9E70. Do not edit by hand; run `make flight-tables`.

const create = @import("../create.zig");

/// How the AI turns a ship of `ship_type` (`create.FlightModel.turns`).
pub fn turns(ship_type: u8) create.FlightModel.Turns {
    return switch (ship_type) {
        0x0C...0x16, 0x1E, 0x20...0x24, 0x33...0x40, 0x42...0xAA, 0xAD...0xF3 => .flat,
        else => .banking,
    };
}
