//! The missions' objectives: for each, the language strings that name its ten objectives,
//! null for none.
//!
//! Generated by `src/tools/tablegen` from the payload executable's objectives table at
//! 0x00504120, 36 rows. Do not edit by hand; run `make objective-tables`.

/// The names of a row's objectives.
pub const Row = [10]?u16;

/// Missions 1 to 35 in turn, then mission 25's second part.
pub const rows = [_]Row{
    .{ 297, 300, null, null, null, null, null, null, null, null }, // 0
    .{ 403, 404, 450, 451, 452, 885, 886, null, null, null }, // 1
    .{ 467, 468, 469, 470, 471, 472, null, null, null, null }, // 2
    .{ 405, 406, 453, 454, 455, null, null, null, null, null }, // 3
    .{ 465, 466, 770, 771, 772, null, null, null, null, null }, // 4
    .{ 407, 408, 409, null, null, null, null, null, null, null }, // 5
    .{ 478, 479, 480, 481, 482, 483, 484, 638, null, null }, // 6
    .{ 416, 417, 418, 419, 456, null, null, null, null, null }, // 7
    .{ 395, 396, 397, 398, 399, 400, 401, 402, 806, 807 }, // 8
    .{ 410, 411, 412, 413, 414, 415, 1384, null, null, null }, // 9
    .{ 625, 626, 627, 628, 629, 630, 631, null, null, null }, // 10
    .{ 457, null, null, null, null, null, null, null, null, null }, // 11
    .{ 596, 597, 598, 599, 600, 601, 602, 603, 604, null }, // 12
    .{ 458, 459, 460, 461, 462, 463, 464, 639, null, null }, // 13
    .{ 390, 391, 392, 393, 889, 890, null, null, null, null }, // 14
    .{ 302, 303, 304, 305, 306, 640, null, null, null, null }, // 15
    .{ 605, 606, 607, 608, 609, 610, 641, null, null, null }, // 16
    .{ 611, 612, 613, 614, 615, 642, 887, 888, null, null }, // 17
    .{ 616, 617, 618, 619, 620, 621, null, null, null, null }, // 18
    .{ 633, 634, 635, 636, 637, 1018, 1019, 1020, 1021, 1245 }, // 19
    .{ 891, 892, 893, 894, 895, 896, 897, null, null, null }, // 20
    .{ null, null, null, null, null, null, null, null, null, null }, // 21
    .{ 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, null, null }, // 22
    .{ 900, 901, 902, 903, 904, 905, null, null, null, null }, // 23
    .{ 1022, 1023, 1024, 1025, null, null, null, null, null, null }, // 24
    .{ 952, 953, 954, 955, 956, 957, 958, 959, null, null }, // 25
    .{ 906, 907, 908, 909, 910, 911, null, null, null, null }, // 26
    .{ 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017 }, // 27
    .{ 968, 969, 970, 971, 972, 973, 974, 975, 977, null }, // 28
    .{ 912, 913, 914, 915, null, null, null, null, null, null }, // 29
    .{ 916, 917, 918, 919, 920, 921, 922, null, null, null }, // 30
    .{ 1030, 1031, null, null, null, null, null, null, null, null }, // 31
    .{ 1033, 1032, 1034, 1035, null, null, null, null, null, null }, // 32
    .{ 1036, 1037, 1038, 1039, 1040, 1041, 1042, null, null, null }, // 33
    .{ 1028, 1029, null, null, null, null, null, null, null, null }, // 34
    .{ 1026, 1027, 1043, null, null, null, null, null, null, null }, // 35
};
