//! Reads the word of `ship_flight_stats` that the payload holds in its data rather than reading it
//! from `shipstats.bin`: for each ship type, how the AI turns it.
//!
//! The table is 256 records, each a `create.FlightModel`. `stats_load_ships` fills a record's
//! figures from the file and works out its `speed_per_pitch_rate`, and the word at `+0x24` stays as
//! the executable has it.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const create = openreliant.engine.game.create;
const FlightModel = create.FlightModel;
const Turns = FlightModel.Turns;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// `ship_flight_stats`.
pub const table: u32 = 0x004F9E70;

pub const Error = image.Error || error{ NotZero, NotFlag };

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)![]const Turns {
    const records = try reader.records(FlightModel, table, create.ship_type_count);
    const types = try arena.alloc(Turns, create.ship_type_count);
    for (types, records) |*turns, record| turns.* = try parse(record);
    return types;
}

/// The executable's own word of one record, which must be one of the two ways a ship turns, the
/// half word after it empty, or the table is not what this reader knows.
fn parse(record: FlightModel) Error!Turns {
    if (record._unknown_26 != 0) return error.NotZero;
    return switch (record.turns) {
        .banking, .flat => |turns| turns,
        _ => error.NotFlag,
    };
}

/// Writes `flight.zig`: a switch over the ship types, the runs of those that turn flat in its one
/// prong.
pub fn emit(w: *Io.Writer, types: []const Turns) Io.Writer.Error!void {
    try w.print(
        \\//! The word of `ship_flight_stats` that the executable holds rather than `shipstats.bin`: for
        \\//! each ship type, how the AI turns it.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's `ship_flight_stats` at
        \\//! 0x{X:0>8}. Do not edit by hand; run `make flight-tables`.
        \\
        \\const create = @import("../create.zig");
        \\
        \\/// How the AI turns a ship of `ship_type` (`create.FlightModel.turns`).
        \\pub fn turns(ship_type: u8) create.FlightModel.Turns {{
        \\    return switch (ship_type) {{
        \\
    , .{table});
    var first = true;
    var start: usize = 0;
    while (start < types.len) {
        if (types[start] != .flat) {
            start += 1;
            continue;
        }
        var end = start;
        while (end + 1 < types.len and types[end + 1] == .flat) end += 1;
        try w.writeAll(if (first) "        " else ", ");
        first = false;
        if (end == start) {
            try w.print("0x{X:0>2}", .{start});
        } else {
            try w.print("0x{X:0>2}...0x{X:0>2}", .{ start, end });
        }
        start = end + 1;
    }
    if (!first) try w.writeAll(" => .flat,\n");
    try w.writeAll(
        \\        else => .banking,
        \\    };
        \\}
        \\
    );
}

test parse {
    var record = std.mem.zeroes(FlightModel);
    try std.testing.expectEqual(.banking, try parse(record));
    record.turns = .flat;
    try std.testing.expectEqual(.flat, try parse(record));

    // A word the game would take for flat too, but that the reader doesn't know.
    record.turns = @enumFromInt(2);
    try std.testing.expectError(error.NotFlag, parse(record));
    record.turns = .flat;
    record._unknown_26 = 1;
    try std.testing.expectError(error.NotZero, parse(record));
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const records = try allocator.alloc(FlightModel, create.ship_type_count);
    defer allocator.free(records);
    @memset(records, std.mem.zeroes(FlightModel));
    // Two runs that turn flat, one of a single type, and the figures the file will overwrite.
    for (records[0x0C..0x17]) |*record| record.turns = .flat;
    records[0x1E].turns = .flat;
    records[0x1E].max_speed = 160;
    records[0xFF].turns = .flat;
    const region: testing.Region = .{ .va = table, .bytes = std.mem.sliceAsBytes(records) };

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const types = try read(arena, payload);
    try std.testing.expectEqual(create.ship_type_count, types.len);
    try std.testing.expectEqual(.banking, types[0x0B]);
    try std.testing.expectEqual(.flat, types[0x0C]);
    try std.testing.expectEqual(.flat, types[0x1E]);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, types);
    try testing.expectZig(out.written());
    try std.testing.expect(std.mem.indexOf(u8, out.written(), "0x0C...0x16, 0x1E, 0xFF => .flat,") != null);

    // A table with no type that turns flat has only the one prong.
    out.clearRetainingCapacity();
    try emit(&out.writer, &.{ .banking, .banking });
    try testing.expectZig(out.written());
    try std.testing.expect(std.mem.indexOf(u8, out.written(), "=> .flat") == null);
}
