//! Reads the missions' objectives out of the payload: for each mission, the language strings that
//! name its ten objectives.
//!
//! The table is `rows` rows of ten records, four bytes each: a halfword state and a halfword string
//! id, -1 for none. Its first 35 rows are missions 1 to 35, and the last mission 25's second part.
//! Only the names are read: the display's set-up gives every objective its state afresh as a
//! mission starts (`objectives_reset`, `0x00499180`).

const std = @import("std");
const Io = std.Io;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// The objectives table (`mission_objectives`), which `cmd_SetObjective` (`0x00459870`) writes the
/// states of and the objectives window (`hud_window_draw`, `0x00486830`) reads.
pub const table: u32 = 0x00504120;

/// The rows the table holds, and the objectives in each.
pub const rows = 36;
pub const per_row = 10;

/// An objective's record as the payload lays it out.
const Stored = extern struct {
    state: i16,
    name: i16,

    comptime {
        std.debug.assert(@sizeOf(Stored) == 4);
    }
};

/// The names of a row's objectives, null for none.
pub const Row = [per_row]?u16;

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (image.Error || std.mem.Allocator.Error)![]const Row {
    const read_rows = try arena.alloc(Row, rows);
    for (read_rows, 0..) |*row, r| {
        for (row, 0..) |*name, n| {
            const stored = try reader.recordAt(Stored, table, r * per_row + n);
            name.* = std.math.cast(u16, stored.name);
        }
    }
    return read_rows;
}

/// Writes `objectives.zig`.
pub fn emit(w: *Io.Writer, read_rows: []const Row) Io.Writer.Error!void {
    try w.print(
        \\//! The missions' objectives: for each, the language strings that name its ten objectives,
        \\//! null for none.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's objectives table at
        \\//! 0x{X:0>8}, {d} rows. Do not edit by hand; run `make objective-tables`.
        \\
        \\/// The names of a row's objectives.
        \\pub const Row = [{d}]?u16;
        \\
        \\/// Missions 1 to 35 in turn, then mission 25's second part.
        \\pub const rows = [_]Row{{
        \\
    , .{ table, read_rows.len, per_row });
    for (read_rows, 0..) |row, index| {
        try w.writeAll("    .{ ");
        for (row, 0..) |name, n| {
            if (n > 0) try w.writeAll(", ");
            if (name) |id| try w.print("{d}", .{id}) else try w.writeAll("null");
        }
        try w.print(" }}, // {d}\n", .{index});
    }
    try w.writeAll(
        \\};
        \\
    );
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const bytes = try allocator.alloc(u8, rows * per_row * @sizeOf(Stored));
    defer allocator.free(bytes);
    @memset(bytes, 0xFF);
    const region: testing.Region = .{ .va = table, .bytes = bytes };
    region.putRecord(table, Stored{ .state = 2, .name = 297 });
    region.putRecord(table + @sizeOf(Stored), Stored{ .state = 1, .name = 300 });

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const read_rows = try read(arena, payload);
    try std.testing.expectEqual(rows, read_rows.len);
    try std.testing.expectEqual(297, read_rows[0][0].?);
    try std.testing.expectEqual(300, read_rows[0][1].?);
    try std.testing.expectEqual(null, read_rows[0][2]);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, read_rows);
    try testing.expectZig(out.written());
}
